[package]
name = "andromeda-modules"
version = "0.1.0"
authors = ["0xjwtradera <jwtradera@outlook.com>"]
edition = "2021"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.1.6"
cosmwasm-schema = "1.1.6"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }

andromeda-std = { git = "https://github.com/andromedaprotocol/andromeda-core.git", branch = "amp", features=["module_hooks"] }